// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdyfigqyefqtdnooktyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkeWZpZ3F5ZWZxdGRub29rdHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzAxMTUsImV4cCI6MjA3MTcwNjExNX0.dS7ETi2IzM2E1HpZcXLCIUqrDsb6yxwIxlis64PzqMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});